### ISSUE TITLE
Segmentation fault when using short devices names

### ISSUE THREAD

**Issue by IsaacJT** [IsaacJT/kleincom#3]
```
kleincom -R usb2
kleincom v3.2a

port is        : usb2
flowcontrol    : none
baudrate is    : 9600
parity is      : none
databits are   : 8
stopbits are   : 1
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
hangup is      : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv -E
imap is        :
omap is        :
emap is        : crcrlf,delbs,
logfile is     : none
initstring     : none
exit_after is  : not set
exit is        : no


FATAL: fish: 'kleincom -R usb2' terminated by signal SIGSEGV (Adressbereichsfehler)
```
```
gdb kleincom
GNU gdb (GDB) Fedora 10.1-2.fc33
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kleincom...
Reading symbols from .gnu_debugdata for /usr/bin/kleincom...
(No debugging symbols found in .gnu_debugdata for /usr/bin/kleincom)
Missing separate debuginfos, use: dnf debuginfo-install kleincom-1.0-1.fc33.x86_64
(gdb) start -R usb2
Temporary breakpoint 1 at 0x402a50
Starting program: /usr/bin/kleincom -R usb2

Temporary breakpoint 1, 0x0000000000402a50 in main ()
(gdb) c
Continuing.
kleincom v3.2a

port is        : usb2
flowcontrol    : none
baudrate is    : 9600
parity is      : none
databits are   : 8
stopbits are   : 1
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
hangup is      : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv -E
imap is        :
omap is        :
emap is        : crcrlf,delbs,
logfile is     : none
initstring     : none
exit_after is  : not set
exit is        : no


FATAL:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f443e7 in __strlen_avx2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7f443e7 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff7e502a8 in __vfprintf_internal () from /lib64/libc.so.6
#2  0x00007ffff7e6116a in __vsnprintf_internal () from /lib64/libc.so.6
#3  0x0000000000406a15 in fd_vprintf ()
#4  0x0000000000407686 in fatal ()
#5  0x00000000004041b9 in main ()
(gdb)
```

**Comment by DukePowerfist** [comment]
Please try the current version (3.3a) and see if the issue still exists.

**Comment by IsaacJT** [comment]
FIXED
